export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const GET_EXPENSE_SUCCESS = 'GET_EXPENSE_SUCCESSS';
export const GET_EXPENSES_SUCCESS = 'GET_EXPENSES_SUCCESSS';
